[package]
name = "intear-dex-types"
version = "0.1.0"
edition = "2024"

[dependencies]
near-sdk = { version = "5", default-features = false }

[features]
default = ["std"]
abi = ["json", "near-sdk/abi"]
json = ["std"]
std = []
